name: Build EA Matrix APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v2
    - run: chmod +x gradlew
    - run: ./gradlew assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: EA-Matrix-APK
        path: app/build/outputs/apk/release/app-release.apk
